### ISSUE TITLE
'unicode/stringpiece.h' file not found when running 

### ISSUE THREAD

**Issue by fenimi** [kpu/preprocess#15]
I'm trying to use the preprocess-master and I'm following the instruction from the GitHub readme file. I get this error when running 'make -j4'.  I'm using os mojave 10.14.6. Please how can i resolve this error?

preprocess-master/util/string_piece.hh:58:10: fatal error: 
      'unicode/stringpiece.h' file not found
#include <unicode/stringpiece.h>
         ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [util/CMakeFiles/preprocess_util.dir/file.cc.o] Error 1
make[1]: *** [util/CMakeFiles/preprocess_util.dir/all] Error 2
make: *** [all] Error 2

**Comment by kpu** [comment]
Install ICU?

**Comment by fenimi** [comment]
Yes I have it installed

**Comment by fenimi** [comment]
I was able to figure it out. I added this command: **_set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -I/usr/local/opt/icu4c/include")_**

 in the CMakeLists.txt after the project command near the start of the file

**Comment by kpu** [comment]
When installing in a non-standard path like that, you have to set `CPATH` for the compiler to find it.
