### ISSUE TITLE
Cache util::EndOfFileException

### ISSUE THREAD

**Issue by zuny26** [kpu/preprocess#16]
Hi. During Bitextor testing, we encountered an issue regarding empty lines in cache output. More precisely, if the first line of the input causes the output to be empty, and then there is another occurrence of the same input line, cache crashes with `util::EndOfFileException`

We found out that `util::Pool` initializes with NULL, so `*copy_to` is NULL if `got` is an empty string. 
https://github.com/kpu/preprocess/blob/7f8724573389703ca2febef63136ea93676bd1df/preprocess/cache_main.cc#L97

So, when the second occurrence of the first line is read, the check in `Input` function passes,
https://github.com/kpu/preprocess/blob/7f8724573389703ca2febef63136ea93676bd1df/preprocess/cache_main.cc#L62-L63,
but so does the one in `Output`:
https://github.com/kpu/preprocess/blob/7f8724573389703ca2febef63136ea93676bd1df/preprocess/cache_main.cc#L91-L93
`value.data()` returns false, even though the copy of the output was stored in the cache, and therefore the input line was not passed to the child process.

One workaround would be to allocate a byte before the loop, to make sure NULL pointer isn’t returned: `char *small_init = (char*)string_pool.Allocate(1);`

Alternatively, the check in the `Input` function could be changed to check the same thing as in the `Output` function, so change `if (res.second)` to `if (!res.first->second.data())`. This way, if the first line produces an empty output, it would be executed twice instead of once, but no errors.

**Comment by kpu** [comment]
Good point, followed your suggested fix.
