### ISSUE TITLE
Error Cmake

### ISSUE THREAD

**Issue by binhvq** [kpu/preprocess#3]
CMake Error at util/CMakeLists.txt:68 (find_package):
  By not providing "FindICU.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "ICU", but
  CMake did not find one.

  Could not find a package configuration file provided by "ICU" with any of
  the following names:

    ICUConfig.cmake
    icu-config.cmake

  Add the installation prefix of "ICU" to CMAKE_PREFIX_PATH or set "ICU_DIR"
  to a directory containing one of the above files.  If "ICU" provides a
  separate development package or SDK, be sure it has been installed.

-- Configuring incomplete, errors occurred!
See also "/home/preprocess/build/CMakeFiles/CMakeOutput.log".

**Comment by kpu** [comment]
Try a newer cmake.  I admit the minimum version in CMakeLists.txt should be increased so you get that error message instead.

**Comment by binhvq** [comment]
My Cmake version is: `2.8.12.2`, in `CMakeLists.txt` `cmake_minimum_required(VERSION 2.6)`
`cmake --version`
`cmake version 2.8.12.2`
I try in fedora 28 and centos 7
Thanks!
