### ISSUE TITLE
Error when compiling with cmake:

### ISSUE THREAD

**Issue by starshine360** [kpu/preprocess#39]
When I compile it with cmake at the branch `wet`，something is wrong. Is there any suggestion?

version of gcc: 9.3.0
version of cmake: 3.27.4
architecture: linux x86_64

Here is the error messages as below:
![image](https://github.com/kpu/preprocess/assets/45736998/a7fa3c59-fd69-452b-9f25-f356f89d45fd)

**Comment by kpu** [comment]
I think your boost install is broken.  Possible causes are:
1. Boost wasn't compiled with the same compiler as you are using.  Boost is very sensitive to this.  
2. Installed headers don't match installed libraries.  
Try compiling the boost program options tutorial at https://www.boost.org/doc/libs/1_83_0/doc/html/program_options/tutorial.html .  If that doesn't work, then boost is definitely broken.

**Comment by starshine360** [comment]
Thanks for your suggestion. The reason is that some libraries (e.g.  program_options) of boost are not built. Now I make it.
