### ISSUE TITLE
Corpus Tokenization

### ISSUE THREAD

**Issue by ndvbd** [kpu/preprocess#7]
The lmplz takes a text file (corpus) and generate ARPA file from it.
However, we need to tokenize the running text before creating the ARPA file, for example separating the punctuation, etc. 
What command in this library takes a running text file and creates another running text file, but with the required spaces?

**Comment by kpu** [comment]
`text.sh $language $lower` where language is ISO 639-1 (though in practice it really only works for Latin and Cyrillic languages) and lower is 0 or 1 based on whether you want to lowercase.

**Comment by ndvbd** [comment]
The thing is that it replaces apostrophes with &apos;
Where is the tokenization algorithm described?

**Comment by kpu** [comment]
Preprocessing is an endless battle of customization.  Look at the implementation of `text.sh` and pick your favorites, particularly the Moses tokenizer  `/moses/tokenizer/tokenizer.perl -l $language`.
